<?php

declare(strict_types=1);

namespace Maloun\QAOrchestrator\Actions;

use Exception;
use Illuminate\Support\Facades\Log;
use Maloun\QAOrchestrator\Enums\TestCaseStatusEnum;
use Maloun\QAOrchestrator\Models\QAProcess;
use Maloun\QAOrchestrator\Services\ClaudeService;
use Maloun\QAOrchestrator\Services\GitHubService;

class AnalyzeTestResultsAction
{
    public function __construct(
        private readonly ClaudeService $claudeService,
        private readonly GitHubService $gitHubService,
    ) {}

    public function handle(QAProcess $qaProcess, int $workflowRunId, string $conclusion): array
    {
        Log::info('AnalyzeTestResultsAction: Analyzing test results', [
            'qa_process_id' => $qaProcess->id,
            'run_id' => $workflowRunId,
            'conclusion' => $conclusion,
        ]);

        $qaProcess->update(['workflow_run_id' => $workflowRunId]);

        $workflowResults = $this->fetchWorkflowResults($workflowRunId);

        $this->updateTestCaseStatuses($qaProcess, $workflowResults);

        $analysis = $this->claudeService->analyzeTestResults(
            testResults: $workflowResults,
            jiraSummary: $qaProcess->jira_summary ?? '',
            jiraDescription: $qaProcess->jira_description,
        );

        $qaProcess->update([
            'test_results' => array_merge($qaProcess->test_results ?? [], [
                'workflow_run_id' => $workflowRunId,
                'conclusion' => $conclusion,
                'raw_results' => $workflowResults,
                'analysis' => $analysis,
            ]),
        ]);

        if ($qaProcess->github_pr_number) {
            $this->addPrComment($qaProcess, $analysis, $conclusion);
        }

        Log::info('AnalyzeTestResultsAction: Analysis complete', [
            'qa_process_id' => $qaProcess->id,
            'summary' => $analysis['summary'] ?? '',
        ]);

        return $analysis;
    }

    private function fetchWorkflowResults(int $runId): array
    {
        try {
            $jobs = $this->gitHubService->getWorkflowRunJobs($runId);

            $results = [];

            foreach ($jobs['jobs'] ?? [] as $job) {
                $results[] = [
                    'name' => $job['name'],
                    'status' => $job['status'],
                    'conclusion' => $job['conclusion'],
                    'steps' => array_map(fn ($step) => [
                        'name' => $step['name'],
                        'status' => $step['status'],
                        'conclusion' => $step['conclusion'],
                    ], $job['steps'] ?? []),
                ];
            }

            return $results;
        } catch (Exception $e) {
            Log::warning('AnalyzeTestResultsAction: Failed to fetch workflow results', [
                'run_id' => $runId,
                'error' => $e->getMessage(),
            ]);

            return [];
        }
    }

    private function updateTestCaseStatuses(QAProcess $qaProcess, array $workflowResults): void
    {
        $overallSuccess = true;

        foreach ($workflowResults as $job) {
            if ($job['conclusion'] !== 'success') {
                $overallSuccess = false;
                break;
            }
        }

        $status = $overallSuccess ? TestCaseStatusEnum::Passed : TestCaseStatusEnum::Failed;

        $qaProcess->testCases()->update(['status' => $status]);
    }

    private function addPrComment(QAProcess $qaProcess, array $analysis, string $conclusion): void
    {
        $emoji = $conclusion === 'success' ? '✅' : '❌';
        $status = $conclusion === 'success' ? 'Passed' : 'Failed';

        $comment = "## {$emoji} Test Results: {$status}\n\n";
        $comment .= "### Summary\n";
        $comment .= ($analysis['summary'] ?? 'No summary available')."\n\n";

        if (! empty($analysis['failures'])) {
            $comment .= "### Failures\n";

            foreach ($analysis['failures'] as $failure) {
                $comment .= "- **{$failure['test']}**: {$failure['reason']}\n";
            }

            $comment .= "\n";
        }

        if (! empty($analysis['recommendations'])) {
            $comment .= "### Recommendations\n";

            foreach ($analysis['recommendations'] as $rec) {
                $comment .= "- {$rec}\n";
            }
        }

        $comment .= "\n---\n";
        $comment .= "_Analysis generated by QA Orchestrator_\n";

        try {
            $this->gitHubService->addPrComment($qaProcess->github_pr_number, $comment);
        } catch (Exception $e) {
            Log::warning('AnalyzeTestResultsAction: Failed to add PR comment', [
                'pr_number' => $qaProcess->github_pr_number,
                'error' => $e->getMessage(),
            ]);
        }
    }
}