<?php

declare(strict_types=1);

namespace Maloun\QAOrchestrator\Actions;

use Exception;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Maloun\QAOrchestrator\Models\QAProcess;
use Maloun\QAOrchestrator\Models\QATestCase;
use Maloun\QAOrchestrator\Services\GitHubService;

class CreateGitHubPrAction
{
    public function __construct(
        private readonly GitHubService $gitHubService,
    ) {}

    public function handle(QAProcess $qaProcess): void
    {
        Log::info('CreateGitHubPrAction: Creating GitHub PR', [
            'qa_process_id' => $qaProcess->id,
        ]);

        $testResults = $qaProcess->test_results ?? [];
        $playwrightCode = $testResults['playwright_code'] ?? null;
        $filePath = $testResults['playwright_file'] ?? null;

        if (! $playwrightCode || ! $filePath) {
            Log::warning('CreateGitHubPrAction: No Playwright code to commit', [
                'qa_process_id' => $qaProcess->id,
            ]);

            return;
        }

        $branchName = $this->generateBranchName($qaProcess);

        $this->gitHubService->createBranch($branchName);

        $this->gitHubService->createOrUpdateFile(
            branch: $branchName,
            path: $filePath,
            content: $playwrightCode,
            message: "test(e2e): add generated tests for {$qaProcess->jira_issue_key}",
        );

        $prBody = $this->generatePrBody($qaProcess);

        $pr = $this->gitHubService->createPullRequest(
            title: "test(e2e): {$qaProcess->jira_issue_key} - {$qaProcess->jira_summary}",
            body: $prBody,
            head: $branchName,
        );

        $qaProcess->update([
            'github_branch' => $branchName,
            'github_pr_url' => $pr['html_url'] ?? null,
            'github_pr_number' => $pr['number'] ?? null,
        ]);

        $this->triggerTests($qaProcess, $branchName);

        Log::info('CreateGitHubPrAction: Created GitHub PR', [
            'qa_process_id' => $qaProcess->id,
            'pr_url' => $qaProcess->github_pr_url,
        ]);
    }

    private function generateBranchName(QAProcess $qaProcess): string
    {
        $issueKey = Str::lower($qaProcess->jira_issue_key);
        $timestamp = now()->format('Ymd-His');

        return "qa/{$issueKey}-{$timestamp}";
    }

    private function generatePrBody(QAProcess $qaProcess): string
    {
        $testCases = $qaProcess->testCases()->get();

        $body = "## AI-Generated E2E Tests\n\n";
        $body .= "**Jira Ticket:** [{$qaProcess->jira_issue_key}]({$qaProcess->jira_issue_url})\n\n";
        $body .= "### Test Cases\n\n";

        /** @var QATestCase $testCase */
        foreach ($testCases as $testCase) {
            $body .= "- [ ] {$testCase->title}\n";
        }

        $body .= "\n### Summary\n\n";
        $body .= $qaProcess->jira_summary."\n\n";

        $body .= "---\n";
        $body .= "_This PR was automatically generated by the QA Orchestrator._\n";

        return $body;
    }

    private function triggerTests(QAProcess $qaProcess, string $branchName): void
    {
        try {
            $this->gitHubService->createRepositoryDispatch('qa-e2e-tests', [
                'qa_process_id' => $qaProcess->id,
                'branch' => $branchName,
                'jira_key' => $qaProcess->jira_issue_key,
            ]);
        } catch (Exception $e) {
            Log::warning('CreateGitHubPrAction: Failed to trigger tests', [
                'qa_process_id' => $qaProcess->id,
                'error' => $e->getMessage(),
            ]);
        }
    }
}